### ISSUE TITLE
script ends without doing anything

### ISSUE THREAD

**Issue by steeegh** [AndDiSa/android_backup_project#3]
full-restoring script could end without producing any effect

<code>$` ./full-restore.sh --data-backup /mnt/hgfs/H/abb/qcom_2020-05-05_QKQ1.190828.002

parm: /mnt/hgfs/H/abb/qcom_2020-05-05_QKQ1.190828.002
/mnt/hgfs/H/abb/busybox-ndk /mnt/hgfs/H/abb
Already up to date.
/mnt/hgfs/H/abb
Waiting for device...
Devices detected:
List of devices attached
cc00e850	device

Checking for root access...
1) Requesting adbd as root...
adbd cannot run as root in production builds
Waiting for device...
shell
root
Determining architecture...
Pushing busybox to device...
busybox-ndk/busybox-arm64: 1 file pushed. 14.5 MB/s (1478208 bytes in 0.097s)
restoring from /mnt/hgfs/H/abb/qcom_2020-05-05_QKQ1.190828.002
## Stop Runtime
/mnt/hgfs/H/abb/qcom_2020-05-05_QKQ1.190828.002 /mnt/hgfs/H/abb
Restoring full tar backup of /data excluding /data/media ... 
3,31MiB 0:00:00 [50,0MiB/s] [50,0MiB/s]

</code>

**Comment by AndDiSa** [comment]
Is the device rooted? If yes, which OS and which rootng method? As written the scripts will work only with root access.

**Comment by AndDiSa** [comment]
@roboroberto please try the latest version and install the AndroidBackupRestore - Magisk Module which should fix permission issues. If this still does not work for you, please send a logcat while doing the restore.
